import type { ModelEntry } from './types';

// The single source of truth for every toy model. Index pages and the
// cross-link matrix are derived from this list (see ./index.ts) — to add a
// model, add one entry here. Only `qv-correlation-lab` ships live today; the
// rest are `planned` and surface as "Planned" cards until built.
//
// The 🔴 "marginal" ideas from docs/CONTENT_PLAN.md are intentionally omitted.
export const MODELS: ModelEntry[] = [
  // ── QuantViz (Finance) ────────────────────────────────────────────────────
  {
    id: 'qv-correlation-lab',
    title: 'Diversification & Correlation Lab',
    studio: 'quantviz',
    tools: ['correlation', 'networks'],
    blurb: 'Build a portfolio and watch the rolling correlation heatmap reveal true diversification.',
    status: 'live',
    route: '/quantviz',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'qv-random-walk',
    title: 'Random Walk vs. Real Markets',
    studio: 'quantviz',
    tools: ['stochastic'],
    blurb: 'Overlay a geometric Brownian motion on real prices and test the random-walk hypothesis.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'qv-monte-carlo',
    title: 'Monte Carlo Portfolio Paths',
    studio: 'quantviz',
    tools: ['stochastic', 'distributions'],
    blurb: 'Simulate thousands of future paths to see the distribution of outcomes and ruin risk.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'qv-efficient-frontier',
    title: 'Efficient Frontier Optimizer',
    studio: 'quantviz',
    tools: ['optimization', 'linear-algebra'],
    blurb: 'Drag portfolio weights and trace the mean–variance frontier to the tangency portfolio.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'qv-eigenportfolios',
    title: 'Factor & Eigenportfolio Decomposition',
    studio: 'quantviz',
    tools: ['linear-algebra'],
    blurb: 'Run PCA on returns to uncover the hidden factors that move the whole market.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'qv-mean-reversion',
    title: 'Mean Reversion & Pairs Trading',
    studio: 'quantviz',
    tools: ['dynamical-systems', 'stochastic', 'detection'],
    blurb: 'Model a spread as an Ornstein–Uhlenbeck process with Kalman-tracked hedge ratios.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'qv-fat-tails',
    title: 'Fat Tails & Value-at-Risk',
    studio: 'quantviz',
    tools: ['distributions'],
    blurb: 'Compare empirical returns to a Gaussian and see why “6-sigma” days keep happening.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'qv-moving-averages',
    title: 'Moving Averages as Filters',
    studio: 'quantviz',
    tools: ['convolution'],
    blurb: 'Treat SMA/EMA as convolution kernels and feel the smoothing-versus-lag tradeoff.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'solid',
  },
  {
    id: 'qv-vol-clustering',
    title: 'Volatility Clustering',
    studio: 'quantviz',
    tools: ['correlation', 'stochastic'],
    blurb: 'Use the autocorrelation of squared returns to expose calm and stormy regimes.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'qv-regime-detection',
    title: 'Regime Detection',
    studio: 'quantviz',
    tools: ['markov'],
    blurb: 'Infer bull/bear/sideways states with a two-state hidden Markov model.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'qv-correlation-networks',
    title: 'Correlation Networks & Systemic Risk',
    studio: 'quantviz',
    tools: ['networks', 'correlation'],
    blurb: 'Turn the correlation matrix into a graph to see clusters and contagion pathways.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },

  // ── NeuroLearn (Neuroscience) ─────────────────────────────────────────────
  {
    id: 'nl-lif',
    title: 'Leaky Integrate-and-Fire Neuron',
    studio: 'neurolearn',
    tools: ['dynamical-systems', 'stochastic'],
    blurb: 'Watch a membrane potential charge to threshold under step, ramp, and sinusoidal input.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'nl-fitzhugh-nagumo',
    title: 'FitzHugh–Nagumo Phase Plane',
    studio: 'neurolearn',
    tools: ['dynamical-systems'],
    blurb: 'Explore nullclines and limit cycles in a 2D excitable system that spikes all-or-none.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'nl-hodgkin-huxley',
    title: 'Hodgkin–Huxley Action Potential',
    studio: 'neurolearn',
    tools: ['dynamical-systems'],
    blurb: 'See ion-channel conductances conspire to generate the real action-potential waveform.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'nl-spike-stats',
    title: 'Spike-Train Statistics',
    studio: 'neurolearn',
    tools: ['stochastic', 'distributions'],
    blurb: 'Generate Poisson spike trains and study ISI histograms, Fano factor, and refractoriness.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'nl-cross-correlogram',
    title: 'Cross-Correlogram & Connectivity',
    studio: 'neurolearn',
    tools: ['correlation'],
    blurb: 'Correlate two spike trains to infer who is driving whom in a circuit.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'nl-receptive-fields',
    title: 'Receptive Fields & Convolution',
    studio: 'neurolearn',
    tools: ['convolution'],
    blurb: 'Treat a visual receptive field as a convolution kernel that performs edge detection.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'nl-brain-rhythms',
    title: 'Brain Rhythms & EEG Explorer',
    studio: 'neurolearn',
    tools: ['fourier'],
    blurb: 'Decompose neural signals into delta–gamma bands with a live spectrogram.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'nl-drift-diffusion',
    title: 'Drift-Diffusion Decision Model',
    studio: 'neurolearn',
    tools: ['stochastic', 'detection'],
    blurb: 'Accumulate noisy evidence to a bound and predict reaction-time distributions.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'nl-signal-detection',
    title: 'Signal Detection Theory',
    studio: 'neurolearn',
    tools: ['detection'],
    blurb: 'Slide the criterion across hits and false alarms to build ROC curves and read d′.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'nl-stdp',
    title: 'Hebbian Learning & STDP',
    studio: 'neurolearn',
    tools: ['optimization'],
    blurb: '“Fire together, wire together” — visualize spike-timing-dependent plasticity.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'nl-neural-manifolds',
    title: 'Population Dynamics & Neural Manifolds',
    studio: 'neurolearn',
    tools: ['linear-algebra'],
    blurb: 'Use PCA to collapse many neurons into a low-dimensional state trajectory.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'nl-neural-coding',
    title: 'Neural Coding & Mutual Information',
    studio: 'neurolearn',
    tools: ['information'],
    blurb: 'Quantify how many bits about a stimulus a spike train actually carries.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'nl-hopfield',
    title: 'Hopfield Attractor Memory',
    studio: 'neurolearn',
    tools: ['dynamical-systems', 'linear-algebra'],
    blurb: 'Drop a partial cue into an energy landscape and watch a memory complete itself.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },

  // ── SignalViz (Signal Processing) ─────────────────────────────────────────
  {
    id: 'sv-fourier-builder',
    title: 'Fourier Builder & Spectrum Analyzer',
    studio: 'signalviz',
    tools: ['fourier'],
    blurb: 'Add sine waves to build a signal and watch its spectrum assemble in real time.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'sv-convolution',
    title: 'Convolution Visualizer',
    studio: 'signalviz',
    tools: ['convolution'],
    blurb: 'Slide a kernel across a signal to build intuition for impulse response and LTI systems.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'sv-filter-designer',
    title: 'Digital Filter Designer',
    studio: 'signalviz',
    tools: ['convolution', 'fourier'],
    blurb: 'Design FIR/IIR low-, high-, and band-pass filters and watch the frequency response.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'sv-aliasing',
    title: 'Sampling & Aliasing',
    studio: 'signalviz',
    tools: ['fourier'],
    blurb: 'Under-sample a signal below Nyquist and watch a wagon-wheel alias appear.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'sv-spectrogram',
    title: 'Spectrogram & Time-Frequency Studio',
    studio: 'signalviz',
    tools: ['fourier'],
    blurb: 'Take the STFT of chirps, speech, and music to navigate the time–frequency tradeoff.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'sv-cross-correlation',
    title: 'Cross-Correlation & Time-Delay',
    studio: 'signalviz',
    tools: ['correlation', 'detection'],
    blurb: 'Slide one signal against another to recover the lag of an echo.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'flagship',
  },
  {
    id: 'sv-beamforming',
    title: 'Sensor Array & Beamforming',
    studio: 'signalviz',
    tools: ['correlation', 'linear-algebra'],
    blurb: 'Use correlation across many sensors to pick out a wavefront and its direction.',
    status: 'planned',
    difficulty: 'advanced',
    strength: 'flagship',
  },
  {
    id: 'sv-matched-filter',
    title: 'Matched Filter & Radar Detection',
    studio: 'signalviz',
    tools: ['detection', 'correlation'],
    blurb: 'Detect a known pulse buried in noise — the optimal detector in action.',
    status: 'planned',
    difficulty: 'core',
    strength: 'flagship',
  },
  {
    id: 'sv-kalman',
    title: 'Kalman Filter Tracker',
    studio: 'signalviz',
    tools: ['detection'],
    blurb: 'Track a noisy moving target through the predict–update loop.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'sv-noise-snr',
    title: 'Noise & SNR Lab',
    studio: 'signalviz',
    tools: ['stochastic', 'convolution'],
    blurb: 'Generate white/pink/brown noise and recover a signal by filtering and averaging.',
    status: 'planned',
    difficulty: 'intro',
    strength: 'solid',
  },
  {
    id: 'sv-source-separation',
    title: 'PCA / ICA Source Separation',
    studio: 'signalviz',
    tools: ['linear-algebra'],
    blurb: 'Unmix overlapping signals — the cocktail-party problem solved.',
    status: 'planned',
    difficulty: 'advanced',
    strength: 'solid',
  },
  {
    id: 'sv-channel-capacity',
    title: 'Channel Capacity & Coding',
    studio: 'signalviz',
    tools: ['information'],
    blurb: 'Push bits through a noisy channel and bump against the Shannon limit.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
  {
    id: 'sv-compression',
    title: 'Transform Coding & Compression',
    studio: 'signalviz',
    tools: ['fourier', 'information'],
    blurb: 'Throw away DCT coefficients JPEG-style and watch quality degrade gracefully.',
    status: 'planned',
    difficulty: 'core',
    strength: 'solid',
  },
];
